# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddPurchase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(627, 370)
        Dialog.setMinimumSize(QtCore.QSize(396, 370))
        Dialog.setMaximumSize(QtCore.QSize(3960, 3700))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog.setStyleSheet("QLineEdit {\n"
"     border: 1px solid gray;\n"
"     border-radius: 15px;\n"
"     padding: 0 8px;\n"
"     background: white;\n"
"     selection-background-color: darkgray;\n"
" }")
        Dialog.setModal(True)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(0, -10, 631, 371))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(40, 160, 71, 20))
        self.label_4.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(40, 200, 71, 20))
        self.label_6.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"")
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(200, 240, 361, 71))
        self.textEdit.setStyleSheet("\n"
"     border: 1px solid gray;\n"
"     border-radius: 5px;\n"
"     padding: 0 8px;\n"
"     background: white;\n"
"     selection-background-color: darkgray;\n"
" ")
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 51, 20))
        self.label_2.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 120, 191, 31))
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 332, 371, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
"background-color: #00394D;\n"
"border-radius:15px;\n"
"color:white;\n"
"font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #0083b3;\n"
"border-radius:15px;\n"
"\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 131, 20))
        self.label_3.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 200, 221, 31))
        self.lineEdit_6.setStyleSheet("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(40, 250, 71, 20))
        self.label_8.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"")
        self.label_8.setObjectName("label_8")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(0, 0, 631, 61))
        self.frame.setStyleSheet("background-color: #00394D;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(250, 30, 131, 21))
        self.label.setStyleSheet("font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox.setGeometry(QtCore.QRect(200, 160, 181, 31))
        self.doubleSpinBox.setStyleSheet("padding-right: 15px; /* make room for the arrows */\n"
"\n"
" border-width: 3;\n"
"border-radius:10px;\n"
" border: 1px solid gray;")
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.dateEdit = QtWidgets.QDateEdit(self.frame_2)
        self.dateEdit.setGeometry(QtCore.QRect(200, 80, 171, 31))
        self.dateEdit.setStyleSheet("\n"
"     border: 1px solid gray;\n"
"     border-radius: 10px;\n"
"     padding: 0 8px;\n"
"     background: white;\n"
"     selection-background-color: darkgray;\n"
" ")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Item"))
        self.label_4.setText(_translate("Dialog", "QUANTITY :"))
        self.label_6.setText(_translate("Dialog", "SUPPLIER :"))
        self.label_2.setText(_translate("Dialog", "DATE :"))
        self.pushButton_2.setToolTip(_translate("Dialog", "Save item to stock."))
        self.pushButton_2.setText(_translate("Dialog", "SAVE PURCHASE"))
        self.label_3.setText(_translate("Dialog", "TRANSACTION CODE:"))
        self.label_8.setText(_translate("Dialog", "REMARKS :"))
        self.label.setText(_translate("Dialog", "ADD PURCHASE"))



