# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddStock.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(781, 424)
        Dialog.setMinimumSize(QtCore.QSize(781, 424))
        Dialog.setMaximumSize(QtCore.QSize(781, 424))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog.setStyleSheet("QLineEdit {\n"
"     border: 1px solid gray;\n"
"     border-radius: 15px;\n"
"     padding: 0 8px;\n"
"     background: white;\n"
"     selection-background-color: darkgray;\n"
" }\n"
"")
        Dialog.setModal(True)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 81, 16))
        self.label_2.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(230, 80, 71, 16))
        self.label_3.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 200, 81, 16))
        self.label_4.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(230, 200, 51, 16))
        self.label_5.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(470, 200, 61, 16))
        self.label_6.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 71, 16))
        self.label_7.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(250, 260, 61, 16))
        self.label_8.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 380, 371, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
"background-color: #00394D;\n"
"border-radius:15px;\n"
"color:white;\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #0083b3;\n"
"border-radius:15px;\n"
"\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 100, 201, 31))
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(20, 100, 151, 31))
        self.dateEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateEdit.setStyleSheet("")
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(Dialog)
        self.dateEdit_2.setGeometry(QtCore.QRect(20, 280, 151, 31))
        self.dateEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateEdit_2.setStyleSheet("")
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox.setGeometry(QtCore.QRect(20, 220, 151, 31))
        self.doubleSpinBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.doubleSpinBox.setStyleSheet("padding-right: 15px; /* make room for the arrows */\n"
"\n"
" border-width: 3;\n"
"\n"
" border: 1px solid gray;")
        self.doubleSpinBox.setWrapping(False)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox.setAccelerated(False)
        self.doubleSpinBox.setProperty("showGroupSeparator", False)
        self.doubleSpinBox.setMaximum(1000000.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(220, 280, 361, 71))
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.textEdit.setMouseTracking(True)
        self.textEdit.setTabletTracking(True)
        self.textEdit.setStyleSheet("\n"
"     border: 1px solid gray;\n"
"     border-radius: 5px;\n"
"     padding: 0 8px;\n"
"     background: white;\n"
"     selection-background-color: darkgray;\n"
" ")
        self.textEdit.setTabChangesFocus(True)
        self.textEdit.setObjectName("textEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(460, 100, 311, 31))
        self.lineEdit_4.setStyleSheet("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(490, 80, 71, 16))
        self.label_9.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_9.setObjectName("label_9")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 781, 61))
        self.frame.setStyleSheet("background-color: #00394D;\n"
"color:rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(340, 20, 81, 21))
        self.label.setStyleSheet("font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"")
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(220, 220, 201, 31))
        self.spinBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox.setStyleSheet("padding-right: 15px; /* make room for the arrows */\n"
"\n"
" border-width: 3;\n"
"\n"
" border: 1px solid gray;")
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setProperty("showGroupSeparator", True)
        self.spinBox.setMaximum(1000000000)
        self.spinBox.setObjectName("spinBox")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(220, 160, 201, 31))
        self.lineEdit_5.setStyleSheet("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(230, 140, 81, 20))
        self.label_10.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_10.setObjectName("label_10")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(20, 160, 151, 31))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(20, 140, 81, 20))
        self.label_11.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(470, 140, 101, 16))
        self.label_12.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_12.setObjectName("label_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(460, 160, 311, 31))
        self.lineEdit_7.setStyleSheet("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 140, 41, 21))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(57, 114, 171);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(470, 220, 301, 31))
        self.comboBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(720, 200, 41, 21))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    background-color: rgb(57, 114, 171);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2.setBuddy(self.dateEdit)
        self.label_3.setBuddy(self.lineEdit_3)
        self.label_4.setBuddy(self.doubleSpinBox)
        self.label_5.setBuddy(self.spinBox)
        self.label_6.setBuddy(self.comboBox_2)
        self.label_7.setBuddy(self.dateEdit_2)
        self.label_8.setBuddy(self.textEdit)
        self.label_9.setBuddy(self.lineEdit_4)
        self.label_10.setBuddy(self.lineEdit_5)
        self.label_11.setBuddy(self.comboBox)
        self.label_12.setBuddy(self.lineEdit_7)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.dateEdit, self.lineEdit_3)
        Dialog.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        Dialog.setTabOrder(self.lineEdit_4, self.comboBox)
        Dialog.setTabOrder(self.comboBox, self.pushButton_3)
        Dialog.setTabOrder(self.pushButton_3, self.lineEdit_5)
        Dialog.setTabOrder(self.lineEdit_5, self.lineEdit_7)
        Dialog.setTabOrder(self.lineEdit_7, self.doubleSpinBox)
        Dialog.setTabOrder(self.doubleSpinBox, self.spinBox)
        Dialog.setTabOrder(self.spinBox, self.comboBox_2)
        Dialog.setTabOrder(self.comboBox_2, self.pushButton_4)
        Dialog.setTabOrder(self.pushButton_4, self.dateEdit_2)
        Dialog.setTabOrder(self.dateEdit_2, self.textEdit)
        Dialog.setTabOrder(self.textEdit, self.pushButton_2)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Item"))
        self.label_2.setText(_translate("Dialog", "DATE ADDED :"))
        self.label_3.setText(_translate("Dialog", "ITEM CODE :"))
        self.label_4.setText(_translate("Dialog", "NO. OF ITEMS"))
        self.label_5.setText(_translate("Dialog", "PRICE :"))
        self.label_6.setText(_translate("Dialog", "SUPPLIER :"))
        self.label_7.setText(_translate("Dialog", "EXPIRY DATE :"))
        self.label_8.setText(_translate("Dialog", "REMARKS :"))
        self.pushButton_2.setToolTip(_translate("Dialog", "Save item to stock."))
        self.pushButton_2.setText(_translate("Dialog", "SAVE ITEM"))
        self.dateEdit.setDisplayFormat(_translate("Dialog", "d/M/yyyy"))
        self.label_9.setText(_translate("Dialog", "ITEM NAME :"))
        self.label.setText(_translate("Dialog", "ADD  ITEM"))
        self.lineEdit_5.setPlaceholderText(_translate("Dialog", "e.g brand, color, shape e.t.c,,"))
        self.label_10.setText(_translate("Dialog", "DESCRIPTION :"))
        self.label_11.setText(_translate("Dialog", "CATEGORY :"))
        self.label_12.setText(_translate("Dialog", "MEASUREMENTS :"))
        self.lineEdit_7.setPlaceholderText(_translate("Dialog", "e.g: ml, cm, kg, g, watts e.t.c"))
        self.pushButton_3.setToolTip(_translate("Dialog", "click to add new category"))
        self.pushButton_3.setText(_translate("Dialog", "+"))
        self.pushButton_4.setToolTip(_translate("Dialog", "click to add new category"))
        self.pushButton_4.setText(_translate("Dialog", "+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
