# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddStock.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(645, 413)
        Dialog.setMinimumSize(QtCore.QSize(645, 413))
        Dialog.setMaximumSize(QtCore.QSize(645, 413))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog.setStyleSheet("QLineEdit {\n"
"     border: 1px solid gray;\n"
"     border-radius: 15px;\n"
"     padding: 0 8px;\n"
"     background: white;\n"
"     selection-background-color: darkgray;\n"
" }\n"
"")
        Dialog.setModal(True)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 51, 16))
        self.label_2.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(190, 80, 71, 16))
        self.label_3.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 61, 16))
        self.label_4.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(190, 140, 51, 16))
        self.label_5.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 200, 61, 16))
        self.label_6.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(410, 140, 71, 16))
        self.label_7.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 260, 61, 16))
        self.label_8.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 370, 371, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
"background-color: #00394D;\n"
"border-radius:15px;\n"
"color:white;\n"
"font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #0083b3;\n"
"border-radius:15px;\n"
"\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 100, 191, 31))
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(20, 220, 361, 31))
        self.lineEdit_6.setStyleSheet("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(20, 100, 110, 31))
        self.dateEdit.setStyleSheet("")
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(Dialog)
        self.dateEdit_2.setGeometry(QtCore.QRect(410, 160, 110, 31))
        self.dateEdit_2.setStyleSheet("")
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox.setGeometry(QtCore.QRect(20, 160, 111, 31))
        self.doubleSpinBox.setStyleSheet("padding-right: 15px; /* make room for the arrows */\n"
"\n"
" border-width: 3;\n"
"\n"
" border: 1px solid gray;")
        self.doubleSpinBox.setWrapping(False)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox.setAccelerated(False)
        self.doubleSpinBox.setProperty("showGroupSeparator", False)
        self.doubleSpinBox.setMaximum(1000000.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 280, 361, 71))
        self.textEdit.setMouseTracking(True)
        self.textEdit.setTabletTracking(True)
        self.textEdit.setStyleSheet("\n"
"     border: 1px solid gray;\n"
"     border-radius: 5px;\n"
"     padding: 0 8px;\n"
"     background: white;\n"
"     selection-background-color: darkgray;\n"
" ")
        self.textEdit.setTabChangesFocus(True)
        self.textEdit.setObjectName("textEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(410, 100, 201, 31))
        self.lineEdit_4.setStyleSheet("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(410, 80, 71, 16))
        self.label_9.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.label_9.setObjectName("label_9")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 701, 61))
        self.frame.setStyleSheet("background-color: #00394D;\n"
"color:rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(290, 20, 81, 21))
        self.label.setStyleSheet("font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(474, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"background-color: green;\n"
"border:none;\n"
"color:white;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(2, 90, 39);\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(190, 160, 171, 31))
        self.spinBox.setStyleSheet("padding-right: 15px; /* make room for the arrows */\n"
"\n"
" border-width: 3;\n"
"\n"
" border: 1px solid gray;")
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMaximum(1000000000)
        self.spinBox.setObjectName("spinBox")
        self.label_2.setBuddy(self.dateEdit)
        self.label_3.setBuddy(self.lineEdit_3)
        self.label_4.setBuddy(self.doubleSpinBox)
        self.label_6.setBuddy(self.lineEdit_6)
        self.label_7.setBuddy(self.dateEdit_2)
        self.label_8.setBuddy(self.textEdit)
        self.label_9.setBuddy(self.lineEdit_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButton, self.dateEdit)
        Dialog.setTabOrder(self.dateEdit, self.lineEdit_3)
        Dialog.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        Dialog.setTabOrder(self.lineEdit_4, self.doubleSpinBox)
        Dialog.setTabOrder(self.doubleSpinBox, self.dateEdit_2)
        Dialog.setTabOrder(self.dateEdit_2, self.lineEdit_6)
        Dialog.setTabOrder(self.lineEdit_6, self.textEdit)
        Dialog.setTabOrder(self.textEdit, self.pushButton_2)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Item"))
        self.label_2.setText(_translate("Dialog", "DATE :"))
        self.label_3.setText(_translate("Dialog", "ITEM CODE :"))
        self.label_4.setText(_translate("Dialog", "QUANTITY :"))
        self.label_5.setText(_translate("Dialog", "PRICE :"))
        self.label_6.setText(_translate("Dialog", "SUPPLIER :"))
        self.label_7.setText(_translate("Dialog", "EXPIRY DATE :"))
        self.label_8.setText(_translate("Dialog", "REMARKS :"))
        self.pushButton_2.setToolTip(_translate("Dialog", "Save item to stock."))
        self.pushButton_2.setText(_translate("Dialog", "SAVE ITEM"))
        self.lineEdit_6.setPlaceholderText(_translate("Dialog", "supplier\'s company name/ owner"))
        self.dateEdit.setDisplayFormat(_translate("Dialog", "d/M/yyyy"))
        self.label_9.setText(_translate("Dialog", "ITEM NAME :"))
        self.label.setText(_translate("Dialog", "ADD  ITEM"))
        self.pushButton.setToolTip(_translate("Dialog", "Search for iem in existing stock."))
        self.pushButton.setText(_translate("Dialog", "Search and Manage Items"))

