# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InventoryReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(954, 579)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 971, 581))
        self.frame.setStyleSheet("background-color: rgb(238, 255, 254);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 0, 201, 61))
        self.label.setMinimumSize(QtCore.QSize(201, 61))
        self.label.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 60, 701, 521))
        self.frame_2.setMinimumSize(QtCore.QSize(561, 491))
        self.frame_2.setStyleSheet("border:2px solid grey;\n"
"border-top-right-radius:15px;\n"
"border-top-left-radius:15px;\n"
"border-bottom:none;\n"
"background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(580, 10, 101, 31))
        self.label_2.setStyleSheet("border:none;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 113, 166);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(580, 40, 101, 20))
        self.label_3.setStyleSheet("border:none;\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(580, 60, 101, 20))
        self.label_4.setStyleSheet("border:none;\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(580, 80, 101, 20))
        self.label_5.setStyleSheet("border:none;\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 130, 701, 271))
        self.tableWidget.setStyleSheet("border:0.5px solid black;\n"
"border-radius:1px;")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(730, 80, 51, 31))
        self.label_6.setMinimumSize(QtCore.QSize(51, 31))
        self.label_6.setStyleSheet("border:none;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 113, 166);")
        self.label_6.setObjectName("label_6")
        self.clearButton = QtWidgets.QPushButton(self.frame)
        self.clearButton.setGeometry(QtCore.QRect(840, 80, 75, 23))
        self.clearButton.setMinimumSize(QtCore.QSize(75, 23))
        self.clearButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    color: rgb(0, 104, 152);\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 0);\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"    text-decoration: underline;\n"
"}")
        self.clearButton.setObjectName("clearButton")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(750, 120, 41, 20))
        self.label_7.setStyleSheet("border:none;\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(750, 160, 31, 20))
        self.label_8.setStyleSheet("border:none;\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_8.setObjectName("label_8")
        self.dateEditFrom = QtWidgets.QDateEdit(self.frame)
        self.dateEditFrom.setGeometry(QtCore.QRect(840, 120, 101, 22))
        self.dateEditFrom.setMinimumSize(QtCore.QSize(101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dateEditFrom.setFont(font)
        self.dateEditFrom.setStyleSheet("border:1px solid grey;")
        self.dateEditFrom.setWrapping(False)
        self.dateEditFrom.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEditFrom.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditFrom.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.dateEditFrom.setCalendarPopup(True)
        self.dateEditFrom.setTimeSpec(QtCore.Qt.TimeZone)
        self.dateEditFrom.setObjectName("dateEditFrom")
        self.dateEditTo = QtWidgets.QDateEdit(self.frame)
        self.dateEditTo.setGeometry(QtCore.QRect(840, 160, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dateEditTo.setFont(font)
        self.dateEditTo.setStyleSheet("border:1px solid grey;")
        self.dateEditTo.setWrapping(False)
        self.dateEditTo.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEditTo.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditTo.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.dateEditTo.setCalendarPopup(True)
        self.dateEditTo.setTimeSpec(QtCore.Qt.TimeZone)
        self.dateEditTo.setObjectName("dateEditTo")
        self.radioButtonPaid = QtWidgets.QRadioButton(self.frame)
        self.radioButtonPaid.setGeometry(QtCore.QRect(760, 200, 41, 17))
        self.radioButtonPaid.setObjectName("radioButtonPaid")
        self.radioButtonNotPaid = QtWidgets.QRadioButton(self.frame)
        self.radioButtonNotPaid.setGeometry(QtCore.QRect(830, 200, 61, 20))
        self.radioButtonNotPaid.setObjectName("radioButtonNotPaid")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(770, 230, 51, 16))
        self.label_9.setObjectName("label_9")
        self.comboBoxItemCode = QtWidgets.QComboBox(self.frame)
        self.comboBoxItemCode.setGeometry(QtCore.QRect(770, 250, 171, 31))
        self.comboBoxItemCode.setStyleSheet("border:1px solid grey;\n"
"border-radius:10px;\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.comboBoxItemCode.setObjectName("comboBoxItemCode")
        self.comboBoxItemCode.addItem("")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(770, 290, 51, 16))
        self.label_10.setObjectName("label_10")
        self.comboBoxItemName = QtWidgets.QComboBox(self.frame)
        self.comboBoxItemName.setGeometry(QtCore.QRect(770, 310, 171, 31))
        self.comboBoxItemName.setStyleSheet("border:1px solid grey;\n"
"border-radius:10px;\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.comboBoxItemName.setObjectName("comboBoxItemName")
        self.comboBoxItemName.addItem("")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(770, 350, 51, 16))
        self.label_12.setObjectName("label_12")
        self.comboBoxSupplier = QtWidgets.QComboBox(self.frame)
        self.comboBoxSupplier.setGeometry(QtCore.QRect(770, 370, 171, 31))
        self.comboBoxSupplier.setStyleSheet("border:1px solid grey;\n"
"border-radius:10px;\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.comboBoxSupplier.setObjectName("comboBoxSupplier")
        self.comboBoxSupplier.addItem("")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(760, 410, 71, 21))
        self.label_11.setStyleSheet("border:none;\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 113, 166);")
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(760, 430, 81, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(760, 450, 61, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(760, 470, 81, 21))
        self.label_15.setObjectName("label_15")
        self.pushButtonPrint = QtWidgets.QPushButton(self.frame)
        self.pushButtonPrint.setGeometry(QtCore.QRect(860, 530, 91, 31))
        self.pushButtonPrint.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    font: 75 13pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 117, 0);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 0);\n"
"    font: 15pt \"MS Shell Dlg 2\";\n"
"    text-decoration: underline;\n"
"    background-color: rgb(170, 255, 255);\n"
"}")
        self.pushButtonPrint.setObjectName("pushButtonPrint")
        self.TotalInventory = QtWidgets.QLabel(self.frame)
        self.TotalInventory.setGeometry(QtCore.QRect(850, 430, 101, 20))
        self.TotalInventory.setStyleSheet("QLabel{\n"
"\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"}")
        self.TotalInventory.setAlignment(QtCore.Qt.AlignCenter)
        self.TotalInventory.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.TotalInventory.setObjectName("TotalInventory")
        self.TotalPaid = QtWidgets.QLabel(self.frame)
        self.TotalPaid.setGeometry(QtCore.QRect(850, 450, 101, 20))
        self.TotalPaid.setStyleSheet("QLabel{\n"
"\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"}")
        self.TotalPaid.setAlignment(QtCore.Qt.AlignCenter)
        self.TotalPaid.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.TotalPaid.setObjectName("TotalPaid")
        self.TotalNotPaid = QtWidgets.QLabel(self.frame)
        self.TotalNotPaid.setGeometry(QtCore.QRect(850, 470, 101, 20))
        self.TotalNotPaid.setStyleSheet("QLabel{\n"
"\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"}")
        self.TotalNotPaid.setAlignment(QtCore.Qt.AlignCenter)
        self.TotalNotPaid.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.TotalNotPaid.setObjectName("TotalNotPaid")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Inventory Reports"))
        self.label_2.setText(_translate("Dialog", "Report info"))
        self.label_3.setText(_translate("Dialog", "French montana"))
        self.label_4.setText(_translate("Dialog", "French montana"))
        self.label_5.setText(_translate("Dialog", "French montana"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "item code"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "item name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "stock"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "price"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "date"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "suplier"))
        self.label_6.setText(_translate("Dialog", "Filter"))
        self.clearButton.setText(_translate("Dialog", "clear all"))
        self.label_7.setText(_translate("Dialog", "From:"))
        self.label_8.setText(_translate("Dialog", "TO:"))
        self.radioButtonPaid.setText(_translate("Dialog", "Paid"))
        self.radioButtonNotPaid.setText(_translate("Dialog", "Not Paid"))
        self.label_9.setText(_translate("Dialog", "item code"))
        self.comboBoxItemCode.setItemText(0, _translate("Dialog", "All item code"))
        self.label_10.setText(_translate("Dialog", "Item Name"))
        self.comboBoxItemName.setItemText(0, _translate("Dialog", "Item Name"))
        self.label_12.setText(_translate("Dialog", "supplier"))
        self.comboBoxSupplier.setItemText(0, _translate("Dialog", "Supplier Name"))
        self.label_11.setText(_translate("Dialog", "Summary"))
        self.label_13.setText(_translate("Dialog", "Total inventory:"))
        self.label_14.setText(_translate("Dialog", "Total paid:"))
        self.label_15.setText(_translate("Dialog", "Total Not Paid:"))
        self.pushButtonPrint.setText(_translate("Dialog", "Print"))
        self.TotalInventory.setText(_translate("Dialog", "200l"))
        self.TotalPaid.setText(_translate("Dialog", "200l"))
        self.TotalNotPaid.setText(_translate("Dialog", "200l"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
