# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notifyframe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_notifyframe(object):
    def setupUi(self, notifyframe):
        notifyframe.setObjectName("notifyframe")
        notifyframe.resize(976, 132)
        self.horizontalLayout = QtWidgets.QHBoxLayout(notifyframe)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.name_label = QtWidgets.QLabel(notifyframe)
        self.name_label.setMinimumSize(QtCore.QSize(300, 0))
        self.name_label.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("")
        self.name_label.setText("")
        self.name_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_label.setWordWrap(True)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 1, 1, 1)
        self.expiry_date = QtWidgets.QLabel(notifyframe)
        self.expiry_date.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.expiry_date.setFont(font)
        self.expiry_date.setText("")
        self.expiry_date.setObjectName("expiry_date")
        self.gridLayout.addWidget(self.expiry_date, 0, 4, 1, 1)
        self.itemcode = QtWidgets.QLabel(notifyframe)
        self.itemcode.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.itemcode.setFont(font)
        self.itemcode.setText("")
        self.itemcode.setObjectName("itemcode")
        self.gridLayout.addWidget(self.itemcode, 0, 0, 1, 1)
        self.category = QtWidgets.QLabel(notifyframe)
        self.category.setText("")
        self.category.setObjectName("category")
        self.gridLayout.addWidget(self.category, 0, 2, 1, 1)
        self.text_1 = QtWidgets.QLabel(notifyframe)
        self.text_1.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_1.setFont(font)
        self.text_1.setStyleSheet("color: rgb(30, 104, 16);\n"
"")
        self.text_1.setText("")
        self.text_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_1.setObjectName("text_1")
        self.gridLayout.addWidget(self.text_1, 0, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(notifyframe)
        QtCore.QMetaObject.connectSlotsByName(notifyframe)

    def retranslateUi(self, notifyframe):
        _translate = QtCore.QCoreApplication.translate
        notifyframe.setWindowTitle(_translate("notifyframe", "Frame"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    notifyframe = QtWidgets.QFrame()
    ui = Ui_notifyframe()
    ui.setupUi(notifyframe)
    notifyframe.show()
    sys.exit(app.exec_())
